version: "3.9"

services:
  db:
    image: postgres:16
    container_name: dietiestates-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: dietiestates
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # solo per accesso da host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dietiestates"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: dietiestates-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  uploads_data: